name: 'Allure report generator V1'
description: 'Generate Allure report for test suite'
inputs:
  workspace-dir:  # id of input
    description: 'Github workspace directory'
    required: true
    default: '/github/workspace'
  report-dir:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workspace-dir }}
    - ${{ inputs.report-dir }}
